import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createRequire} from 'node:module';
import {instantiateV4,buildV4Genesis,buildV4Transition,publicV4Journal,derivePublicV4RecoveryPlan} from '../src/public-v4-protocol.mjs';import {signPublicAssetPlan,validatePublicAssetPlan} from '../src/public-asset-signing.mjs';
const sdk=createRequire(import.meta.url)('../.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa'),templates=JSON.parse(await readFile('.cache/public-templates/templates.json','utf8')).templates,keys=[1,2].map(n=>new sdk.PrivateKey(n.toString().padStart(2,'0').repeat(32))),owners=keys.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()),addresses=keys.map(k=>k.toAddress('testnet-10').toString()),state={worldId:'44'.repeat(32),owner:owners[0],x:1,y:1,energy:3,maxFee:3000000};
const source=()=>new sdk.UtxoEntries([{outpoint:{transactionId:'ab'.repeat(32),index:0},amount:1000000000n,scriptPublicKey:sdk.payToAddressScript(new sdk.Address(addresses[0])),blockDaaScore:0n,isCoinbase:false}]).items;
const genesis=()=>buildV4Genesis(sdk,{kind:'terrarium',templates,states:[state],cellAmounts:[20000000n],fundingUtxos:source(),changeAddress:addresses[0]});
async function sign(p){await signPublicAssetPlan(p,(tx,i,s)=>sdk.createInputSignature(tx,i,keys[owners.indexOf(s.owner)]));return p;}
const cell=p=>({asset:instantiateV4(sdk,templates.terrarium,'terrarium',state),utxo:new sdk.UtxoEntries([{outpoint:{transactionId:p.transaction.id,index:0},amount:p.transaction.outputs[0].value,scriptPublicKey:p.transaction.outputs[0].scriptPublicKey,covenant_id:p.covenantId,blockDaaScore:0n,isCoinbase:false}]).items[0]});
test('V4 exact signed genesis and transition recover without accepting observation metadata',async()=>{const g=await sign(genesis()),p=await sign(buildV4Transition(sdk,{kind:'terrarium',templates,cells:[cell(g)],states:[{...state,x:2,energy:2}],operation:0}));for(const plan of [g,p]){const j=publicV4Journal(plan),r=derivePublicV4RecoveryPlan(sdk,{templates,journal:j,keysPublic:owners});assert.equal(r.transaction.serializeToSafeJSON(),plan.transaction.serializeToSafeJSON());for(const changed of [{...j,accepted:true},{...j,id:'ff'.repeat(32)},{...j,kind:'unknown'}])assert.throws(()=>derivePublicV4RecoveryPlan(sdk,{templates,journal:changed,keysPublic:owners}));}p.states[0].energy=99;assert.throws(()=>validatePublicAssetPlan(p),/changed/);});
test('V4 recovery rejects modified operation, source state, output state and signing owners',async()=>{const g=await sign(genesis()),p=await sign(buildV4Transition(sdk,{kind:'terrarium',templates,cells:[cell(g)],states:[{...state,x:2,energy:2}],operation:0})),j=publicV4Journal(p);for(const mutate of [j=>j.operation=1,j=>j.inputStates[0].energy=4,j=>j.states[0].x=0,j=>j.feeOutputIndex=9,j=>j.genesis=[state]]){const changed=structuredClone(j);mutate(changed);assert.throws(()=>derivePublicV4RecoveryPlan(sdk,{templates,journal:changed,keysPublic:owners}));}assert.throws(()=>derivePublicV4RecoveryPlan(sdk,{templates,journal:j,keysPublic:[owners[1]]}),/owners/);});
test('V4 construction rejects changed template, foreign lineage and principal overflow',async()=>{const g=await sign(genesis()),c=cell(g);assert.throws(()=>buildV4Transition(sdk,{kind:'terrarium',templates,cells:[{...c,asset:{...c.asset,kind:'bundle'}}],states:[{...state,x:2,energy:2}],operation:0}),/template/);assert.throws(()=>buildV4Genesis(sdk,{kind:'terrarium',templates,states:[state],cellAmounts:[100000001n],fundingUtxos:source(),changeAddress:addresses[0]}),/at most/);assert.throws(()=>instantiateV4(sdk,templates.terrarium,'terrarium',{...state,unknown:1}),/fields/);});
