import{test}from'node:test';import assert from'node:assert/strict';import{createRequire}from'node:module';import{readFile}from'node:fs/promises';import{instantiatePublicArgent,buildPublicArgentGenesis,buildPublicArgentFeed,buildPublicArgentRetire,signPublicArgentPlan,validatePublicArgentPlan,publicArgentJournal,derivePublicArgentRecoveryPlan}from'../src/public-argent-protocol.mjs';
const sdk=createRequire(import.meta.url)('../.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa'),templates=JSON.parse(await readFile('src/public-argent-templates.json')),keys=[1,2].map(n=>new sdk.PrivateKey(n.toString().padStart(2,'0').repeat(32))),owners=keys.map(k=>k.toPublicKey().toXOnlyPublicKey().toString());
const funding=()=>new sdk.UtxoEntries([{outpoint:{transactionId:'ab'.repeat(32),index:0},amount:1000000000n,scriptPublicKey:sdk.payToAddressScript(keys[0].toAddress('testnet-10')),blockDaaScore:0n,isCoinbase:false}]).items;
const sign=p=>signPublicArgentPlan(p,(tx,i,s)=>sdk.createInputSignature(tx,i,keys[owners.indexOf(s.owner)]));
const cell=(p,actor,i=0)=>({asset:instantiatePublicArgent(sdk,templates,actor,p.states[i]),utxo:new sdk.UtxoEntries([{outpoint:{transactionId:p.transaction.id,index:i},amount:p.transaction.outputs[i].value,scriptPublicKey:p.transaction.outputs[i].scriptPublicKey,covenant_id:p.transaction.outputs[i].covenant.covenantId.toString(),blockDaaScore:0n,isCoinbase:false}]).items[0]});
async function ready(){const w=await sign(buildPublicArgentGenesis(sdk,{templates,actor:'warden',state:{owner:owners[0],food:9},deposit:25000000n,fundingUtxos:funding()})),c=await sign(buildPublicArgentGenesis(sdk,{templates,actor:'creature',state:{owner:owners[0],controller_id:w.covenantId,energy:1},deposit:25000000n,fundingUtxos:funding()}));return{w,c,warden:cell(w,'warden'),creature:cell(c,'creature')};}
test('Argent generated genesis, closed ICC and owner exits recover exact signed bytes',async()=>{const r=await ready(),feed=await sign(buildPublicArgentFeed(sdk,{templates,...r,quantity:2})),exit=await sign(buildPublicArgentRetire(sdk,{templates,actor:'creature',cell:cell(feed,'creature',1)}));for(const p of[r.w,r.c,feed,exit]){const j=publicArgentJournal(p),restored=derivePublicArgentRecoveryPlan(sdk,{templates,journal:j,keysPublic:owners});assert.equal(restored.transaction.serializeToSafeJSON(),p.transaction.serializeToSafeJSON());}assert.equal(feed.states[0].food,7);assert.equal(feed.states[1].energy,3);assert.equal(feed.transaction.outputs[1].value,r.creature.utxo.amount);assert.equal(feed.calls[0].args.length,5,'Argent hidden template witnesses included');});
test('Argent signer rejects modified review metadata and outputs before signing',async()=>{for(const mutate of[p=>p.states[1].energy++,p=>p.calls[0].args[1]++,p=>p.signers[0].owner=owners[1],p=>p.transaction.outputs[0].value--]){const r=await ready(),p=buildPublicArgentFeed(sdk,{templates,...r,quantity:1});mutate(p);assert.throws(()=>validatePublicArgentPlan(p),/changed/);}});
test('Argent recovery refuses forged state, ICC operation, signatures, owner and chain claims',async()=>{const r=await ready(),p=await sign(buildPublicArgentFeed(sdk,{templates,...r,quantity:1})),j=publicArgentJournal(p);for(const mutate of[j=>j.states[1].energy++,j=>j.quantity=2,j=>j.operation='retire',j=>j.inputStates[1].controller_id='ef'.repeat(32),j=>j.acceptingBlock='ef'.repeat(32),j=>{const tx=JSON.parse(j.transaction);tx.inputs[0].signatureScript='00';j.transaction=JSON.stringify(tx);}]){const changed=structuredClone(j);mutate(changed);assert.throws(()=>derivePublicArgentRecoveryPlan(sdk,{templates,journal:changed,keysPublic:owners}));}assert.throws(()=>derivePublicArgentRecoveryPlan(sdk,{templates,journal:j,keysPublic:[owners[1]]}),/owned keys/);});
test('Argent construction rejects foreign controller, overfeeding, wrong template and duplicate funding',async()=>{const r=await ready();assert.throws(()=>buildPublicArgentFeed(sdk,{templates,...r,quantity:4}),/policy/);assert.throws(()=>buildPublicArgentFeed(sdk,{templates,...r,creature:{...r.creature,asset:{...r.creature.asset,script:'00'}},quantity:1}),/template/);assert.throws(()=>buildPublicArgentFeed(sdk,{templates,...r,quantity:10}),/policy/);const inputs=funding();assert.throws(()=>buildPublicArgentGenesis(sdk,{templates,actor:'warden',state:{owner:owners[0],food:9},deposit:25000000n,fundingUtxos:[inputs[0],inputs[0]]}),/Duplicate/);});

test('Argent app recovery clears cached observations and rebuilds only surviving outputs',async()=>{const{validatePublicArgentState,derivePublicArgentCells,createPublicArgentUI}=await import('../src/public-argent-ui.mjs'),r=await ready(),feed=await sign(buildPublicArgentFeed(sdk,{templates,...r,quantity:1})),retire=await sign(buildPublicArgentRetire(sdk,{templates,actor:'creature',cell:cell(feed,'creature',1)})),activity=[r.w,r.c,feed,retire].map(p=>({journal:publicArgentJournal(p),checkpoint:'ab'.repeat(32),observed:true,applied:true,acceptingBlock:'cd'.repeat(32)}));const alive=derivePublicArgentCells(sdk,templates,[...activity].reverse(),owners);assert.equal(alive.length,1);assert.equal(alive[0].asset.kind,'warden');assert.equal(alive[0].asset.state.food,8);assert.equal(createPublicArgentUI({context:()=>({sdk,argentTemplates:templates,owners}),getState:()=>({version:1,activity})}).view().nextAction,'retire-warden');const clean=validatePublicArgentState(sdk,templates,{version:1,activity:structuredClone(activity)},owners);assert(clean.activity.every(r=>!r.observed&&!r.applied&&!r.acceptingBlock));assert.equal(derivePublicArgentCells(sdk,templates,clean.activity,owners).length,0);assert.throws(()=>validatePublicArgentState(sdk,templates,{version:1,activity:[activity[0],activity[0]]},owners),/repeated/);});

test('public Argent blocks new spending before wallet access while retaining local QA and exits',async()=>{const{publicArgentSpendingEnabled,createPublicArgentUI}=await import('../src/public-argent-ui.mjs');for(const name of ['kaspaexplained.com','preview.pages.dev','localhost.example.com',''])assert.equal(publicArgentSpendingEnabled(name),false);for(const name of ['localhost','127.0.0.1','[::1]'])assert.equal(publicArgentSpendingEnabled(name),true);const previous=Object.getOwnPropertyDescriptor(globalThis,'location');Object.defineProperty(globalThis,'location',{value:{hostname:'kaspaexplained.com'},configurable:true});let walletTouches=0;const controller=createPublicArgentUI({context:()=>({}),getState:()=>undefined,ensureWallet:async()=>{walletTouches++;throw Error('exit reached wallet recovery');}});try{assert.equal(controller.view().newSpendingEnabled,false);for(const action of ['create-warden','create-creature','feed'])await assert.rejects(()=>controller.run(action),/disabled here/);assert.equal(walletTouches,0);await assert.rejects(()=>controller.run('retire-warden'),/exit reached wallet recovery/);assert.equal(walletTouches,1);}finally{if(previous)Object.defineProperty(globalThis,'location',previous);else delete globalThis.location;}});
