import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createRequire} from 'node:module';
import {buildV4Genesis,buildV4Transition,instantiateV4,publicV4Journal,derivePublicV4RecoveryPlan} from '../src/public-v4-protocol.mjs';
import {signPublicAssetPlan} from '../src/public-asset-signing.mjs';
import {buildV4CropGenesis,buildV4CropPurchase,selectV4WageUtxo,deriveV4EconomyEvidence} from '../src/v4-economy-protocol.mjs';
const sdk=createRequire(import.meta.url)('../.cache/upstream/kaspa-wasm32-sdk/nodejs/kaspa'),templates=JSON.parse(await readFile('.cache/public-templates/templates.json','utf8')).templates,keys=[1,2,3].map(n=>new sdk.PrivateKey(n.toString().padStart(2,'0').repeat(32))),owners=keys.map(k=>k.toPublicKey().toXOnlyPublicKey().toString()),addresses=keys.map(k=>k.toAddress('testnet-10').toString()),base={templates,owners,addresses,feeRate:100};
const utxo=(id,index,amount,scriptPublicKey,covenant)=>new sdk.UtxoEntries([{outpoint:{transactionId:id,index},amount,scriptPublicKey,blockDaaScore:0n,isCoinbase:false,...(covenant?{covenant_id:covenant}:{})}]).items[0];
const output=(p,i)=>utxo(p.transaction.id,i,p.transaction.outputs[i].value,p.transaction.outputs[i].scriptPublicKey,p.transaction.outputs[i].covenant?.covenantId.toString());
const cells=p=>(p.genesis||p.states).map((state,i)=>({asset:instantiateV4(sdk,templates[p.kind],p.kind,state),utxo:output(p,i)}));
const fund=()=>utxo('ab'.repeat(32),0,1000000000n,sdk.payToAddressScript(new sdk.Address(addresses[0])));
const sign=async p=>{await signPublicAssetPlan(p,(tx,i,s)=>sdk.createInputSignature(tx,i,keys[owners.indexOf(s.owner)]));return p;};
const record=p=>({journal:publicV4Journal(p),acceptingBlock:'cc'.repeat(32)});
async function setup(){const state={worldId:'44'.repeat(32),owner:owners[0],worker:owners[1],a:3,b:3,c:3,ceiling:6,reward:10000000,maxFee:3000000},g=await sign(buildV4Genesis(sdk,{...base,kind:'compute',states:[state],cellAmounts:[25000000n],fundingUtxos:[fund()],changeAddress:addresses[0]})),w=await sign(buildV4Transition(sdk,{...base,kind:'compute',cells:cells(g),states:[{...state,a:1,b:0,c:2}],operation:0,amounts:[25000000n-10000000n],payments:[{address:addresses[1],amount:10000000n}],feeOutputIndex:0})),wageRecord=record(w),crop=await sign(buildV4CropGenesis(sdk,{...base,wageRecord,fundingUtxos:[output(g,1)]}));return {w,wageRecord,crop,entries:[output(w,1)],records:[record(g),wageRecord,record(crop)]};}
test('Exact accepted worker wage funds crop exchange; signed journal survives restart with explicit fee and change',async()=>{const s=await setup(),p=await sign(buildV4CropPurchase(sdk,{...base,...s,cells:cells(s.crop)}));assert.equal(p.transaction.inputs.length,4);assert.equal(p.transaction.inputs[3].previousOutpoint.transactionId,s.w.transaction.id);assert.equal(p.transaction.inputs[3].previousOutpoint.index,1);assert.equal(p.transaction.outputs[3].value,3000000n);assert.equal(p.transaction.outputs[4].value+BigInt(p.fee),7000000n);assert.equal(p.signers[3].owner,owners[1]);assert(p.states.every(s=>s.owner===owners[1]));const j=publicV4Journal(p),restored=derivePublicV4RecoveryPlan(sdk,{templates,journal:JSON.parse(JSON.stringify(j)),keysPublic:owners});assert.equal(restored.transaction.serializeToSafeJSON(),p.transaction.serializeToSafeJSON());const pending={journal:j},records=[...s.records,pending];let e=deriveV4EconomyEvidence(sdk,{...base,records,wageTransactionId:s.w.transaction.id});assert.equal(e.stage,'purchase-pending');assert.equal(e.purchaseAccepted,false);assert.equal(e.wageReserved,true);pending.acceptingBlock='dd'.repeat(32);e=deriveV4EconomyEvidence(sdk,{...base,records:JSON.parse(JSON.stringify(records)),wageTransactionId:s.w.transaction.id});assert.equal(e.stage,'purchased');assert.equal(e.priceSompi,'3000000');assert.equal(BigInt(e.pipChangeSompi)+BigInt(e.feeSompi),7000000n);assert.throws(()=>selectV4WageUtxo(sdk,{...base,...s,records}),/saved spend/);});
test('Missing wage, substitute funds, wrong crop lineage and excessive fees fail without top-up',async()=>{const s=await setup(),args={...base,...s,cells:cells(s.crop)};assert.throws(()=>buildV4CropPurchase(sdk,{...args,wageRecord:{...s.wageRecord,acceptingBlock:null}}),/accepted/);assert.throws(()=>buildV4CropPurchase(sdk,{...args,entries:[utxo('ff'.repeat(32),1,5000000n,sdk.payToAddressScript(new sdk.Address(addresses[1])))]}),/exact accepted wage/);assert.throws(()=>buildV4CropPurchase(sdk,{...args,entries:[]}),/exact accepted wage/);assert.throws(()=>buildV4CropPurchase(sdk,{...args,records:s.records.map(r=>r.journal.id===s.crop.transaction.id?{...r,acceptingBlock:null}:r)}),/genesis must be accepted/);assert.throws(()=>buildV4CropPurchase(sdk,{...args,cells:args.cells.slice(0,2)}),/three unsold/);assert.throws(()=>buildV4CropPurchase(sdk,{...args,fee:7000000n}),/cover fee|top-up/);assert.throws(()=>buildV4CropGenesis(sdk,{...base,...s,fundingUtxos:s.entries}),/Main must fund/);});
test('Fee growth is bounded by real mass checks and the covenant fee cap',async()=>{const s=await setup(),args={...base,...s,cells:cells(s.crop)},p=buildV4CropPurchase(sdk,args);assert(BigInt(p.mass.storageMass)<=500000n);assert(BigInt(p.fee)<=3000000n);const allowed=[];for(const feeRate of [100,105,110,115,120,200]){try{const p=buildV4CropPurchase(sdk,{...args,feeRate});assert(BigInt(p.mass.storageMass)<=500000n);assert(BigInt(p.fee)<=3000000n);allowed.push(feeRate);}catch(e){assert.match(e.message,/public limits|cover fee/);}}assert(allowed.includes(100));assert(!allowed.includes(120));console.log('Economy accepted fee rates:',allowed.join(', '),'base mass:',p.mass.storageMass,'base fee:',p.fee);});
