// Loopback-only trusted-oracle PoC. Never expose this signing service publicly.
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,rename,stat} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {createWrapEvm} from './wrap-evm.mjs';
import {createWrapKaspa} from './wrap-kaspa.mjs';
const AMOUNT='100000000';
const writeJSON=async(path,value)=>{await writeFile(path+'.tmp',JSON.stringify(value,null,2)+'\n',{mode:0o600});await rename(path+'.tmp',path);};
export async function createWrapPoc({directory='.local/wrap-poc',sourceNetwork='sepolia',port=8912,evmAdapter,kaspaAdapter}={}){
 if(!['local','sepolia'].includes(sourceNetwork))throw Error('Only test networks are allowed.');
 directory=resolve(directory);await mkdir(directory,{recursive:true,mode:0o700});const capability=randomBytes(32).toString('hex'),path=directory+'/bridge-'+sourceNetwork+'.json';
 let journal;try{journal=JSON.parse(await readFile(path,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;journal={version:1,sourceNetwork,claim:null};}if(journal.version!==1||journal.sourceNetwork!==sourceNetwork)throw Error('Bridge journal network mismatch.');
 const evm=evmAdapter||await createWrapEvm({directory,network:sourceNetwork});
 const kaspa=kaspaAdapter||await createWrapKaspa({directory:directory+'/kaspa-'+sourceNetwork,oracleGuard:id=>evm.verifyDeposit(id)});
 let busy=false,message='Prepare free test funds and the source vault to begin.',lastError=null;
 async function view(){const source=await evm.status();let k=await kaspa.status();if(k.pending&&!busy){await kaspa.check();k=await kaspa.status();}const initialized=Boolean(k.init?.accepted),minted=Boolean(k.mint?.accepted),transferred=Boolean(k.transfer?.accepted),burned=Boolean(k.burn?.accepted),released=Boolean(source.deposit?.released),completed=Boolean(released&&burned&&k.burn.depositId===source.deposit.id&&k.burn.covenantId===k.covenantId);const stage=completed?'redeemed':burned?'burned':transferred?'transferred':minted?'issued':source.deposit?'locked':source.ready&&initialized&&BigInt(source.balances.user)>=BigInt(AMOUNT)?'funded':'empty';
  const funding=Number(k.balancesSompi?.[0]||0)>=55000000;
  let nextMessage=message;if(!busy&&!lastError){nextMessage=stage==='redeemed'?'Round trip complete. Pip received all 100 source tokens after the Kaspa claim was burned.':stage==='burned'?'The Kaspa burn was accepted. Release the locked source tokens to Pip.':stage==='transferred'?'Pip owns the 100-unit Kaspa claim. Burn it to release the source tokens.':stage==='issued'?'The oracle issued 100 backed test-asset claims on Kaspa. Transfer them to Pip.':stage==='locked'?(source.deposit.finalized?'The source deposit is finalized. The test oracle can verify it and issue the claim.':'The 100 source tokens are locked. Waiting for the source block to finalize before the oracle issues anything.'):stage==='funded'?'Both test networks are ready. Lock 100 Pixie Test USD in the source vault.':source.networkMode==='sepolia'&&BigInt(source.gasBalanceWei)===0n?'The Sepolia wallet needs free test ETH from a faucet.':'Prepare the test token, source vault and Kaspa issuance contract.';}
  if(released&&!completed)nextMessage='The source deposit was released without the matching accepted burn in this journal. New bridge actions are stopped.';const pending=busy||k.pending||(released&&!completed);
  return {available:true,capability,network:source.network+' → Kaspa Testnet-10',stage,busy,pending:Boolean(k.pending),message:lastError||nextMessage,error:Boolean(lastError),source,kaspa:k,oracle:{trusted:true,policy:'Finalized source deposit before issuance; accepted Kaspa burn before source release.',custody:'This local test service controls the oracle and both demonstration users. No external wallet authorization is claimed.',priceFeed:false},actions:[
   {id:'setup',label:'Prepare free test funds',disabled:pending||stage!=='empty'},
   {id:'lock',label:'Lock 100 pUSD',disabled:pending||stage!=='funded'},
   {id:'mint',label:'Oracle: verify deposit & issue',disabled:pending||stage!=='locked'||!source.deposit?.finalized},
   {id:'transfer',label:'Transfer claim to Pip',disabled:pending||stage!=='issued'},
   {id:'redeem',label:burned?'Release source tokens to Pip':'Burn claim & redeem pUSD',disabled:pending||!['transferred','burned'].includes(stage)},
   {id:'check',label:'Refresh both networks',disabled:busy}
  ]};
 }
 async function fundKaspa(){const k=await kaspa.status();if(BigInt(k.balancesSompi[0])>=55000000n)return;if(!journal.claim){journal.claim={address:k.addresses[0],requestId:randomBytes(16).toString('hex')};await writeJSON(path,journal);}if(journal.claim.address!==k.addresses[0])throw Error('The saved faucet claim belongs to a different wallet.');const response=await fetch('https://kaspa-demo-faucet.parker2017.workers.dev/api/faucet',{method:'POST',headers:{'content-type':'application/json',origin:'http://127.0.0.1:'+port},body:JSON.stringify({address:journal.claim.address,requestId:journal.claim.requestId}),signal:AbortSignal.timeout(30000)});const result=await response.json();if(!response.ok)throw Error(typeof result.error==='string'?result.error:'The Testnet-10 faucet is unavailable.');if(result.network!=='testnet-10'||result.amount!=='1000000000'||!/^[a-f0-9]{64}$/.test(result.transactionId||''))throw Error('Unexpected faucet response.');if(journal.claim.transactionId&&journal.claim.transactionId!==result.transactionId)throw Error('The faucet changed the saved transaction ID.');journal.claim.transactionId=result.transactionId;await writeJSON(path,journal);await kaspa.check();let after=await kaspa.status();for(let attempt=0;attempt<10&&BigInt(after.balancesSompi[0])<55000000n;attempt++){await new Promise(resolve=>setTimeout(resolve,1000));after=await kaspa.status();}if(BigInt(after.balancesSompi[0])<55000000n)throw Error('The test-coin request is saved. Wait for its output, then prepare again; no new request will be created.');}
 async function act(action){if(busy)throw Error('An action is already running. Wait or refresh its saved result.');if(!['setup','lock','mint','transfer','redeem','check'].includes(action))throw Error('Unknown bridge action.');busy=true;lastError=null;message='Checking '+action+'…';try{
   const preflight=action==='check'?null:await view();if(preflight?.source.deposit?.released&&preflight.stage!=='redeemed')throw Error('The source deposit was released without the matching accepted burn. New bridge actions are stopped.');
   if(action==='check'){await kaspa.check();}
   else if(action==='setup'){await evm.initialize();await evm.fundOracle();await evm.faucet();await fundKaspa();await kaspa.init();}
   else {const current=preflight;if(current.kaspa.pending)throw Error('A Kaspa transaction is pending. Check it before starting another action.');
    if(action==='lock'){if(current.stage!=='funded'&&current.stage!=='locked')throw Error('Prepare both networks before locking the source asset.');await evm.lock(current.kaspa.owners[0]);}
    if(action==='mint'){if(!current.source.deposit||!['locked','issued'].includes(current.stage))throw Error('A finalized source deposit is required.');await evm.verifyDeposit(current.source.deposit.id);await kaspa.mint(current.source.deposit.id);}
    if(action==='transfer'){if(!['issued','transferred'].includes(current.stage))throw Error('An accepted Kaspa claim is required.');await kaspa.transfer();}
    if(action==='redeem'){if(!['transferred','burned','redeemed'].includes(current.stage))throw Error('Pip must own the claim before redemption.');if(current.stage!=='redeemed'){await kaspa.burn();await kaspa.check();const k=await kaspa.status();if(!k.burn?.accepted||!k.burn.acceptingBlock||k.burn.depositId!==current.source.deposit.id||k.burn.covenantId!==k.covenantId)throw Error('The expected Kaspa burn is not accepted yet. Source tokens remain locked.');await evm.release(current.source.deposit.id,k.burn.transactionId);}}
   }
  }catch(error){lastError=error.message||'The operation did not complete.';throw error;}finally{busy=false;}return view();}
 const mime={'.html':'text/html; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.wasm':'application/wasm','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.pdf':'application/pdf','.woff2':'font/woff2'};
 const staticRoot=resolve('dist');
 const server=createServer(async(req,res)=>{const json=(code,value)=>{res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(value));};
  try{const allowedHosts=['127.0.0.1:'+port,'localhost:'+port];if(!allowedHosts.includes(req.headers.host))return json(403,{error:'This signing PoC is available only on loopback.'});const url=new URL(req.url,'http://'+req.headers.host);
   if(url.pathname==='/api/wrap-poc/status'&&req.method==='GET')return json(200,await view());
   if(url.pathname==='/api/wrap-poc/action'&&req.method==='POST'){const token=req.headers['x-wrap-capability'];if(req.headers.origin!=='http://'+req.headers.host||typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token)||!timingSafeEqual(Buffer.from(token),Buffer.from(capability)))return json(403,{error:'Reload this local page before using the test oracle.'});let body='';for await(const chunk of req){body+=chunk;if(body.length>1024)return json(413,{error:'Request too large.'});}const value=JSON.parse(body);if(!value||Object.keys(value).some(k=>k!=='action'))return json(400,{error:'Unexpected action fields.'});return json(200,await act(value.action));}
   if(url.pathname.startsWith('/api/'))return json(404,{error:'No such PoC operation.'});if(req.method!=='GET'&&req.method!=='HEAD')return json(405,{error:'Read-only static files.'});let pathname=decodeURIComponent(url.pathname);if(pathname.split('/').some(p=>p.startsWith('.')))return json(404,{error:'Not found.'});if(pathname==='/'||pathname==='/wrap/')pathname='/wrap.html';else if(!extname(pathname))pathname+='.html';const file=resolve(staticRoot,'.'+pathname);if(!file.startsWith(staticRoot+sep))return json(404,{error:'Not found.'});const bytes=await readFile(file);res.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(req.method==='HEAD'?undefined:bytes);
  }catch(error){if(error.code==='ENOENT')return json(404,{error:'Not found.'});return json(400,{error:error.message||'The PoC could not complete this request.'});}
 });
 return {view,act,server,async close(){await Promise.allSettled([evm.close(),kaspa.close()]);if(server.listening)await new Promise(r=>server.close(r));}};
}
if(import.meta.url===pathToFileURL(process.argv[1]||'').href){const port=Number(process.env.WRAP_POC_PORT||8912);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Invalid loopback port.');const app=await createWrapPoc({port,sourceNetwork:process.env.WRAP_EVM_NETWORK||'sepolia'});app.server.listen(port,'127.0.0.1',()=>console.log('Wrapping PoC: http://127.0.0.1:'+port+'/wrap'));for(const signal of ['SIGINT','SIGTERM'])process.on(signal,async()=>{await app.close();process.exit(0);});}
