// Source-chain half of the wrapping PoC. Only a local EVM or Ethereum Sepolia.
// The trusted oracle is explicit: this vault does not verify Kaspa consensus.
import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createRequire} from 'node:module';
import {Wallet,JsonRpcProvider,BrowserProvider,Contract,ContractFactory,Interface,keccak256,parseEther} from '../.cache/wrap-evm/node_modules/ethers/lib.esm/index.js';
const require=createRequire(import.meta.url);
const solc=require('../.cache/wrap-evm/node_modules/solc');
const AMOUNT=100000000n,HEX32=/^0x[0-9a-f]{64}$/i;
const safeReceipt=r=>({hash:r.hash,blockNumber:r.blockNumber,blockHash:r.blockHash,status:r.status,gasUsed:String(r.gasUsed),feeWei:String(r.fee),contractAddress:r.contractAddress||null});
async function readJSON(path,fallback){try{return JSON.parse(await readFile(path,'utf8'));}catch(e){if(e.code==='ENOENT')return fallback;throw e;}}
async function store(path,value){const temporary=path+'.tmp';await writeFile(temporary,JSON.stringify(value,null,2)+'\n',{mode:0o600});await rename(temporary,path);}
export async function createWrapEvm({directory='.local/wrap-poc',network='local'}={}){
 if(!['local','sepolia'].includes(network))throw Error('Only local test EVM and Sepolia are supported.');
 directory=resolve(directory);await mkdir(directory,{recursive:true,mode:0o700});
 async function account(name){const path=directory+'/'+name+'-wallet.json';let saved=await readJSON(path,null);if(!saved){const wallet=Wallet.createRandom();saved={address:wallet.address,privateKey:wallet.privateKey,createdAt:new Date().toISOString()};await store(path,saved);}const wallet=new Wallet(saved.privateKey);if(wallet.address!==saved.address)throw Error('Saved test wallet address does not match.');return wallet;}
 const user=await account('sepolia'),oracle=await account('oracle'),pip=await account('pip-evm'),chainId=network==='local'?31337:11155111;
 const path=directory+'/evm-'+network+'.json';let state=await readJSON(path,{version:1,chainId,transactions:[],token:null,vault:null,deposit:null});if(state.version!==1||state.chainId!==chainId)throw Error('Source-chain journal network mismatch.');
 let provider,local,artifacts;let gate=Promise.resolve();
 const serialized=fn=>{const next=gate.then(fn,fn);gate=next.catch(()=>{});return next;};
 async function connect(){if(provider)return; if(network==='local'){
  const ganache=require('../.cache/wrap-evm/node_modules/ganache');
  local=ganache.provider({chain:{chainId},wallet:{accounts:[user,oracle,pip].map(w=>({secretKey:w.privateKey,balance:'0x'+parseEther('100').toString(16)}))},database:{dbPath:directory+'/local-evm-db'},logging:{quiet:true}});
  provider=new BrowserProvider(local,undefined,{cacheTimeout:-1});
 }else provider=new JsonRpcProvider('https://ethereum-sepolia-rpc.publicnode.com',undefined,{cacheTimeout:-1});
 provider.pollingInterval=1000;if(Number((await provider.getNetwork()).chainId)!==chainId)throw Error('Wrong source chain; sending is blocked.');}
 async function compile(){if(artifacts)return artifacts;const source=await readFile(new URL('../contracts/wrap-poc/TestBridge.sol',import.meta.url),'utf8');const result=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'TestBridge.sol':{content:source}},settings:{optimizer:{enabled:true,runs:200},evmVersion:'shanghai',outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}})));const errors=(result.errors||[]).filter(e=>e.severity==='error');if(errors.length)throw Error(errors.map(e=>e.formattedMessage).join('\n'));artifacts=result.contracts['TestBridge.sol'];return artifacts;}
 async function receiptFor(record){const r=await provider.getTransactionReceipt(record.hash);if(!r)return null;const block=await provider.getBlock(r.blockNumber);if(!block||block.hash!==r.blockHash)throw Error('Source receipt is not in the current canonical chain.');record.receipt=safeReceipt(r);await store(path,state);if(r.status!==1)throw Error('Source transaction reverted. Its journal is retained; no replacement is sent.');return r;}
 async function send(key,wallet,request){await connect();let record=state.transactions.find(r=>r.key===key);if(record){const accepted=await receiptFor(record);if(accepted)return accepted;}else{
  const connected=wallet.connect(provider),nonce=Number(BigInt(await provider.send('eth_getTransactionCount',[wallet.address,'pending'])));
  const populated=await connected.populateTransaction({...request,nonce,chainId});const raw=await wallet.signTransaction(populated),hash=keccak256(raw);
  record={key,hash,raw,from:wallet.address,to:request.to||null,nonce,preparedAt:new Date().toISOString(),receipt:null};state.transactions.push(record);await store(path,state);
 }
 // Retry only the saved bytes. A lost response never creates a second authorization.
 try{await provider.broadcastTransaction(record.raw);}catch(error){if(!await provider.getTransaction(record.hash))throw Error('Source submission is uncertain. Check the saved transaction before retrying: '+error.shortMessage);}
 const r=await provider.waitForTransaction(record.hash,1,60000);if(!r)throw Error('Source transaction is pending; the exact signed transaction is saved.');return receiptFor(record);
 }
 async function contracts(){await connect();const a=await compile();if(!state.token||!state.vault)throw Error('Prepare the source vault first.');for(const [name,address]of [['token',state.token],['vault',state.vault]]){const code=await provider.getCode(address);if(code==='0x'||keccak256(code)!==state[name+'CodeHash'])throw Error('The configured source contract code changed or is missing.');}return {token:new Contract(state.token,a.MockUSD.abi,provider),vault:new Contract(state.vault,a.TestVault.abi,provider)};}
 async function initialize(){return serialized(async()=>{await connect();const a=await compile();if(!state.token){const factory=new ContractFactory(a.MockUSD.abi,a.MockUSD.evm.bytecode.object,user.connect(provider));const r=await send('deploy-token',user,await factory.getDeployTransaction());state.token=r.contractAddress;state.tokenCodeHash=keccak256(await provider.getCode(state.token));await store(path,state);}if(!state.vault){const factory=new ContractFactory(a.TestVault.abi,a.TestVault.evm.bytecode.object,user.connect(provider));const r=await send('deploy-vault',user,await factory.getDeployTransaction(state.token,oracle.address));state.vault=r.contractAddress;state.vaultCodeHash=keccak256(await provider.getCode(state.vault));await store(path,state);}return status();});}
 async function faucet(){return serialized(async()=>{const {token}=await contracts();await send('faucet-test-usd',user,await token.faucet.populateTransaction());return status();});}
 async function lock(kaspaOwner){return serialized(async()=>{if(!/^[a-f0-9]{64}$/i.test(kaspaOwner))throw Error('Expected the exact Kaspa recipient public key.');const {token,vault}=await contracts();if(state.deposit){if(state.deposit.kaspaRecipient.toLowerCase()!=='0x'+kaspaOwner.toLowerCase())throw Error('The saved deposit recipient cannot change.');return status();}await send('approve-source-vault',user,await token.approve.populateTransaction(state.vault,AMOUNT));const r=await send('lock-source-asset',user,await vault.deposit.populateTransaction(AMOUNT,'0x'+kaspaOwner));const iface=new Interface((await compile()).TestVault.abi);const event=r.logs.filter(l=>l.address.toLowerCase()===state.vault.toLowerCase()).map(l=>{try{return {parsed:iface.parseLog(l),index:l.index};}catch{return null;}}).find(e=>e?.parsed?.name==='Deposited');if(!event)throw Error('The expected vault deposit event was not found.');const args=event.parsed.args;if(args.amount!==AMOUNT||args.depositor.toLowerCase()!==user.address.toLowerCase()||args.kaspaRecipient.toLowerCase()!=='0x'+kaspaOwner.toLowerCase())throw Error('The source event did not match the reviewed deposit.');state.deposit={id:args.depositId,transactionId:r.hash,logIndex:event.index,blockNumber:r.blockNumber,blockHash:r.blockHash,amountUnits:String(args.amount),kaspaRecipient:args.kaspaRecipient,sourceChainId:chainId,token:state.token,vault:state.vault};await store(path,state);return status();});}
 async function verifyDeposit(depositId){await connect();const {vault}=await contracts();const d=state.deposit;if(!d||d.id!==depositId||d.sourceChainId!==chainId||d.token!==state.token||d.vault!==state.vault)throw Error('Unknown deposit or source-chain binding.');const tx=state.transactions.find(r=>r.key==='lock-source-asset');const receipt=await receiptFor(tx);if(!receipt||receipt.hash!==d.transactionId||receipt.blockHash!==d.blockHash)throw Error('The source deposit is not currently canonical.');const final=await provider.send('eth_getBlockByNumber',['finalized',false]);if(!final||BigInt(final.number)<BigInt(receipt.blockNumber))throw Error('The source deposit is not finalized yet. Check again when the source chain finalizes its block.');const saved=await vault.deposits(d.id);if(saved.amount!==AMOUNT||saved.released||saved.kaspaRecipient.toLowerCase()!==d.kaspaRecipient.toLowerCase())throw Error('The source deposit is unavailable or differs from the recorded claim.');return {verified:true,depositId:d.id,amountUnits:String(AMOUNT),kaspaOwner:d.kaspaRecipient.slice(2),sourceChainId:chainId,vault:state.vault,token:state.token,transactionId:d.transactionId,logIndex:d.logIndex,blockHash:d.blockHash,finalizedBlockHash:final.hash,oracle:oracle.address};}
 async function release(depositId,burnId){return serialized(async()=>{if(!/^[a-f0-9]{64}$/i.test(burnId))throw Error('An exact Kaspa burn transaction ID is required.');const d=state.deposit;if(!d||d.id!==depositId)throw Error('Unknown source deposit.');const {vault}=await contracts();const existing=state.releaseIntent;if(existing&&(existing.depositId!==depositId||existing.burnId!==burnId||existing.recipient!==pip.address))throw Error('The saved redemption amount, burn or recipient cannot change.');if(!existing){state.releaseIntent={depositId,burnId,recipient:pip.address,amountUnits:String(AMOUNT)};await store(path,state);}await send('release-source-asset',oracle,await vault.release.populateTransaction(depositId,pip.address,'0x'+burnId));return status();});}
 async function status(){await connect();const balances={user:'0',pip:'0',vault:'0'};let released=false,finalized=false;if(state.token&&state.vault){const {token,vault}=await contracts();[balances.user,balances.pip,balances.vault]=await Promise.all([token.balanceOf(user.address),token.balanceOf(pip.address),token.balanceOf(state.vault)]).then(v=>v.map(String));if(state.deposit){released=(await vault.deposits(state.deposit.id)).released;const final=await provider.send('eth_getBlockByNumber',['finalized',false]);finalized=Boolean(final&&BigInt(final.number)>=BigInt(state.deposit.blockNumber));}}return {network:network==='local'?'Local Ethereum test chain':'Ethereum Sepolia',networkMode:network,chainId,local:network==='local',asset:'Pixie Test USD',symbol:'pUSD',decimals:6,amountUnits:String(AMOUNT),ready:Boolean(state.token&&state.vault),userAddress:user.address,pipAddress:pip.address,oracleAddress:oracle.address,gasBalanceWei:String(await provider.getBalance(user.address)),oracleGasBalanceWei:String(await provider.getBalance(oracle.address)),tokenAddress:state.token,vaultAddress:state.vault,balances,deposit:state.deposit?{...state.deposit,finalized,released}:null,releaseIntent:state.releaseIntent||null,transactions:state.transactions.map(({raw,...record})=>({...record,explorer:network==='sepolia'?'https://sepolia.etherscan.io/tx/'+record.hash:null}))};}
 async function fundOracle(){return serialized(async()=>{await connect();if(network==='local')return status();if(await provider.getBalance(oracle.address)>parseEther('0.001'))return status();await send('fund-test-oracle-gas',user,{to:oracle.address,value:parseEther('0.002')});return status();});}
 return {initialize,faucet,lock,verifyDeposit,release,status,fundOracle,async close(){provider?.destroy();if(local)await local.disconnect();}};
}
