import {publicAppsPage} from './public-apps-page.mjs';
export const wrapPage={file:'wrap.html',title:'Wrap lab',description:'Wrap native test KAS or inspect a trusted-oracle test-asset bridge from Ethereum Sepolia to Kaspa Testnet-10.',body:`
<link rel="stylesheet" href="/assets/wrap.css">
<main class="wrap-app" data-wrap-app aria-label="Wrap lab">
<header class="wrap-header"><a class="wrap-brand" href="/wrap">Wrap lab <span>Testnet only</span></a><div class="wrap-header-actions"><button data-wrap-activity>Your transactions</button><button data-wrap-wallet>Wallet</button></div></header>
<div class="wrap-intro"><p class="wrap-eyebrow">A receipt you can redeem</p><h1 data-wrap-heading>Move the claim.<br>Keep the backing.</h1><p data-wrap-intro-text>Lock test coins, send their receipt to Pip, then exchange it for the coins again.</p></div>
<nav class="wrap-experiments" aria-label="Choose an experiment"><button data-wrap-mode="native" aria-pressed="true">Wrap test KAS</button><button data-wrap-mode="external" aria-pressed="false">Bridge a test asset</button></nav>
<section data-wrap-native>
<div class="wrap-balances" aria-label="Current balances"><div><span>Locked backing</span><strong data-wrap-reserve>Not available</strong><small>Test KAS held by the covenant</small></div><div><span>Your receipt</span><strong data-wrap-yours>Not available</strong><small>Claim held by your Main account</small></div><div><span>Pip’s receipt</span><strong data-wrap-pips>Not available</strong><small>Claim held by the Second account</small></div></div>
<div class="wrap-workspace"><section class="wrap-card wrap-operation"><nav class="wrap-tabs" aria-label="Receipt action"><button data-wrap-tab="wrap" aria-pressed="true">1. Wrap</button><button data-wrap-tab="transfer" aria-pressed="false">2. Transfer</button><button data-wrap-tab="redeem" aria-pressed="false">3. Redeem</button></nav><div class="wrap-operation-body"><p class="wrap-eyebrow" data-wrap-step></p><h2 data-wrap-title>Wrap 0.5 test KAS</h2><p data-wrap-description></p><div class="wrap-route"><div><span data-wrap-from-label></span><strong data-wrap-from></strong></div><span aria-hidden="true">→</span><div><span data-wrap-to-label></span><strong data-wrap-to></strong></div></div><p class="wrap-note" data-wrap-availability></p><button class="wrap-primary" data-wrap-prepare>Review wrap</button><button class="wrap-secondary" data-wrap-connect hidden>Create test wallet & get test coins</button></div></section>
<aside class="wrap-card wrap-state"><p class="wrap-eyebrow">Your experiment</p><h2 data-wrap-state-title>Ready when you are</h2><ol class="wrap-steps" data-wrap-steps></ol><div class="wrap-wallet-balances"><span>Your spendable test coins <strong data-wrap-wallet-balance>Not available</strong></span><span>Pip’s spendable test coins <strong data-wrap-pip-balance>Not available</strong></span></div><p class="wrap-note">You control both accounts in this demo. Pip is a second role in the same test wallet, not another person.</p><button data-wrap-check>Check latest state</button></aside></div>
<section class="wrap-card wrap-review" data-wrap-review hidden aria-labelledby="wrap-review-title"><p class="wrap-eyebrow">Review before signing</p><h2 id="wrap-review-title" data-wrap-review-title></h2><p data-wrap-review-summary></p><dl class="wrap-review-facts"><div><dt>Network fee</dt><dd data-wrap-fee></dd></div><div><dt>Fee paid by</dt><dd>Your Main account</dd></div></dl><details><summary>Inspect the exact transaction</summary><div data-wrap-review-details></div></details><div class="wrap-review-actions"><button class="wrap-primary" data-wrap-confirm>Sign & submit</button><button data-wrap-cancel>Cancel</button></div></section>
<section class="wrap-card wrap-records"><div class="wrap-section-heading"><h2>Receipt history</h2><span data-wrap-history-count></span></div><div data-wrap-records><p>No transaction submitted.</p></div></section>
</section>
<section class="wrap-card wrap-external" data-wrap-external hidden><h2>Bridge a test asset</h2><div data-wrap-external-state><p>Loading the recorded test round trip…</p></div><p class="wrap-note">This is a trusted-oracle test. Kaspa does not independently verify the external chain’s consensus.</p></section>
<p class="wrap-status" data-wrap-status role="status" aria-live="polite">Connecting to the testnet application…</p>
<div class="wrap-explanations"><details><summary>What this proves</summary><p><strong>Native receipt.</strong> Test KAS is held in the covenant output. Transfer changes who owns the claim. Redemption consumes it and releases the backing. Only a node-reported accepting block counts as accepted here.</p><p><strong>External bridge.</strong> The source vault holds the test asset. A trusted oracle authorizes issuance on Kaspa and source release after a burn. Source receipts and Kaspa accepting blocks document the transactions. They do not prove that Kaspa independently verified Ethereum’s consensus.</p><p>The recorded bridge shows an external test asset entering and leaving Kaspa. It is separate from the town’s tKAS purchases: wTestUSD cannot buy crops in the town.</p><p>Free test coins have no monetary value. This unaudited experiment is not a mainnet bridge.</p></details><details><summary>Path to real capital</summary><p>Native backing and external custody are different problems. A real external-asset bridge also needs a defined custodian or proof system, reliable deposit and withdrawal handling, independent security review, and clear responsibility when an oracle fails.</p></details></div>
</main><div data-wrap-wallet-shell hidden><div class="wrap-wallet-heading"><h2>Your test wallet</h2><button data-wrap-close-wallet>Back to Wrap lab</button></div>${publicAppsPage.body}</div>`};
